// Offline renderer regression checks: no browser, network or production fixture.
const fs = require('fs'), vm = require('vm'), assert = require('assert');
const context = vm.createContext({performance: {now: () => 0}});
vm.runInContext(fs.readFileSync(__dirname + '/js/home-twin.js', 'utf8') + ';this.twin=HomeTwin;', context);
const twin = context.twin;
twin.update({car:{charge_pct:0}},0);
assert(twin.render(1).includes('>0%</text>'));
assert(!twin.render(1).includes('t-car charging'));
twin.update({car:{charging:true},rooms:{livingroom:{curtain_position:0}}},1);
for(let i=1;i<150;i++) twin.render(1+i/24);
const closed=twin.render(8);
assert(closed.includes('t-car charging'));
assert(closed.includes('class="fabric"'));
twin.update({rooms:{livingroom:{curtain_position:100}}},8);
for(let i=1;i<150;i++) twin.render(8+i/24);
assert.notStrictEqual(closed,twin.render(15));
twin.update({rooms:{porch:{occupied:true}}},15);
for(let i=1;i<25;i++) twin.render(15+i/24);
assert(twin.render(16).includes('lens awake'));
assert(twin.render(16).includes('class="presence"'));
twin.update({},16);
for(let i=1;i<240;i++) twin.render(16+i/24);
const cleared=twin.render(26);
assert(!cleared.includes('lens awake'));
assert(!cleared.includes('class="presence"'));
assert(!cleared.includes('class="fabric"'));
assert(!cleared.includes('class="temperature"'));
console.log('Home renderer regression checks passed');
